application: price-me
version: dev
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: core.views.application

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
